TOP=../..
include $(TOP)/configure/CONFIG
DB += eurothermDis.template
DB += eurothermRec.template
DB += eurothermProg.template
DB += eurothermL1.template
DB += eurothermL2.template
DB += eurotherm3k-archive.template
DB += eurotherm3k-gui.template
DB += eurotherm2k-archive.template
DB += eurotherm2k-gui.template
include $(TOP)/configure/RULES
