TOP=../..
include $(TOP)/configure/CONFIG
DB += eurotherm3504-archive.template
DB += eurotherm3504-gui.template
DB += eurotherm2k-archive.template
DB += eurotherm2k-gui.template
include $(TOP)/configure/RULES
